stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw/application_train.csv
    - src/prepare.py
    outs:
    - data/interim/application_masked.csv
  featurize:
    cmd: python src/featurize.py
    deps:
    - data/interim/application_masked.csv
    - data/raw/bureau.csv
    - data/raw/installments_payments.csv
    - src/featurize.py
    outs:
    - data/processed/train_final.csv
  train:
    cmd: python src/train.py
    deps:
    - data/processed/train_final.csv
    - src/train.py
    outs:
    - models/threshold.json
    - reports/interpretability/feature_importance.png
